PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source TEXT NOT NULL,
  competition_code TEXT NOT NULL,
  season_code TEXT NOT NULL,
  game_code INTEGER NOT NULL,
  game_date TEXT,
  played INTEGER NOT NULL DEFAULT 0,
  home_team_code TEXT,
  home_team_name TEXT,
  away_team_code TEXT,
  away_team_name TEXT,
  home_score REAL,
  away_score REAL,
  raw_json TEXT,
  UNIQUE(source, season_code, game_code)
);

CREATE TABLE IF NOT EXISTS team_games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source TEXT NOT NULL,
  competition_code TEXT NOT NULL,
  season_code TEXT NOT NULL,
  game_code INTEGER NOT NULL,
  game_date TEXT,
  team_code TEXT NOT NULL,
  team_name TEXT,
  opponent_code TEXT NOT NULL,
  opponent_name TEXT,
  home_away TEXT NOT NULL,
  points REAL,
  opponent_points REAL,
  rebounds REAL,
  offensive_rebounds REAL,
  defensive_rebounds REAL,
  assists REAL,
  steals REAL,
  turnovers REAL,
  blocks REAL,
  fouls_committed REAL,
  fouls_received REAL,
  fg2m REAL,
  fg2a REAL,
  fg3m REAL,
  fg3a REAL,
  ftm REAL,
  fta REAL,
  valuation REAL,
  possessions_est REAL,
  raw_json TEXT,
  UNIQUE(source, season_code, game_code, team_code)
);

CREATE TABLE IF NOT EXISTS player_games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source TEXT NOT NULL,
  competition_code TEXT NOT NULL,
  season_code TEXT NOT NULL,
  game_code INTEGER NOT NULL,
  game_date TEXT,
  team_code TEXT NOT NULL,
  team_name TEXT,
  opponent_code TEXT NOT NULL,
  opponent_name TEXT,
  home_away TEXT NOT NULL,
  team_score REAL,
  opponent_score REAL,
  player_code TEXT NOT NULL,
  player_name TEXT NOT NULL,
  position_name TEXT,
  starter INTEGER,
  minutes REAL,
  points REAL,
  rebounds REAL,
  offensive_rebounds REAL,
  defensive_rebounds REAL,
  assists REAL,
  steals REAL,
  turnovers REAL,
  blocks REAL,
  fouls_committed REAL,
  fouls_received REAL,
  plus_minus REAL,
  fg2m REAL,
  fg2a REAL,
  fg3m REAL,
  fg3a REAL,
  ftm REAL,
  fta REAL,
  valuation REAL,
  raw_json TEXT,
  UNIQUE(source, season_code, game_code, player_code)
);

CREATE INDEX IF NOT EXISTS idx_team_games_lookup ON team_games(season_code, team_code, game_date);
CREATE INDEX IF NOT EXISTS idx_player_games_lookup ON player_games(season_code, player_code, game_date);
CREATE INDEX IF NOT EXISTS idx_player_opponent_lookup ON player_games(season_code, opponent_code, position_name, game_date);
